// Generated by CoffeeScript 1.7.1
var docpadConfig;

docpadConfig = {
  plugins: {
    tags: {
      extension: '.html',
      injectDocumentHelper: function(doc) {
        return doc.setMeta({
          layout: 'tag'
        });
      }
    }
  }
};

module.exports = docpadConfig;
